services:
  # PostgreSQL service
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  # Keycloak service added new
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    ports:
      - "9080:8080"
    networks:
      - db
    restart: unless-stopped
    command: start-dev

networks:
  db:
    driver: bridge

volumes:
  db: