services:
  # PostgreSQL service (your existing configuration)
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db_data:/data/postgres # Using a named volume for better management
    ports:
      - "5332:5432"
    networks:
      - app-network # Changed to the shared network
    restart: unless-stopped

  # Keycloak service (your existing configuration)
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
    ports:
      - "9080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - app-network # Changed to the shared network
    restart: unless-stopped
    command: start-dev

  # --- NEW SERVICE ---
  # Open Policy Agent (OPA) Service
  opa:
    container_name: opa
    build:
      context: .
      dockerfile: ./opa/Dockerfile
    ports:
      - "8181:8181"
    networks:
      - app-network
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"  # Bind to all interfaces
      - "--watch"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "/policies"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8181/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

# Define the shared network for all services
networks:
  app-network:
    driver: bridge

# Define the named volume for persistent database storage
volumes:
  db_data:
  keycloak_data:

