services:
  db:   # Service name (you can call it anything, here it's "db")
    container_name: postgres  # The container will be named "postgres"
    image: postgres:latest    # Use the official Postgres image from Docker Hub
    environment:              # Environment variables (like configs)
      POSTGRES_USER: admin    # Username for the database
      POSTGRES_PASSWORD: password    # Password for the database
      PGDATA: /data/postgres         # Location inside the container where data will be stored
    volumes:                 # Volumes = store data persistently
      - db:/data/postgres    # Maps volume "db" to container path "/data/postgres"
    ports:
      - "5332:5432"          # Maps host port 5332 → container port 5432
    networks:
      - db                   # Connects container to "db" network
    restart: unless-stopped  # Restart policy → container auto-restarts unless manually stopped

networks:
  db:                        # Define a custom network named "db"
    driver: bridge           # Uses "bridge" networking mode (default)

volumes:
  db:                        # Define a named volume "db"
